#!/usr/bin/env bash

DISKS_TO_MOUNT=(
    "UUID=20f1c47d-7f9b-4c18-8a22-e1a5fe509ef2    ${HOME}/Documents   ext4    defaults    0 0"
    "UUID=7d366d8b-7b1a-42bc-a4e2-0cd96644d2b9    ${HOME}/2TO         ext4    defaults    0 0"
)

SUCKLESS=(
    "dwm"
)

CUSTOM_SCRIPTS=(
    "grub2-themes"
    "astro_nvim"
    "doom_emacs"
    "lts_kernel"
    "global"
)

AUR_PACKAGES=(
    "joshuto"
    "scrcpy"
    "sddm-sugar-candy-git"
    "spaceship-prompt-git"
)

FLATPAK_PACKAGES=(
    "chat.revolt.RevoltDesktop /var/lib/flatpak/exports/bin/chat.revolt.RevoltDesktop /usr/bin/revolt"
    "com.github.tchx84.Flatseal /var/lib/flatpak/exports/bin/com.github.tchx84.Flatseal /usr/bin/flatseal"
    "com.discordapp.Discord /var/lib/flatpak/exports/bin/com.discordapp.Discord /usr/bin/discord"
    "org.jdownloader.JDownloader /var/lib/flatpak/exports/bin/org.jdownloader.JDownloader /usr/bin/jdownloader"
)

PACMAN_PACKAGES=(
    # xorg
    "xorg-server"
    "xorg-xprop"
    "xorg-xrandr"
    "xorg-xrdb"
    "xorg-xsetroot"

    # display manager
    "sddm"

    # sound
    "alsa-utils"
    "pamixer"
    "pipewire"
    "pipewire-alsa"
    "pipewire-pulse"

    # drivers
    "amd-ucode"
    "libva-mesa-driver"
    "mesa"
    "mesa-vdpau"
    "vulkan-radeon"
    "xf86-video-amdgpu"
    "xf86-video-ati"

    # dwm
    "alacritty"
    "base-devel"
    "gnu-free-fonts"

    # apps
    "docker"
    "docker-compose"
    "firefox"
    "flatpak"
    "gimp"
    "gnome-keyring"
    "lxappearance"
    "nemo"
    "nemo-fileroller"
    "ncdu"
    "nextcloud-client"
    "openssh"
    "pavucontrol"
    "rsync"
    "scrcpy"
    "swtpm"
    "xdg-user-dirs"
    ## rust (install `rustup` before `rust-analyzer` otherwise `rust` is installed)
    "rustup"
    "rust-analyzer"
    ## android
    "gvfs-mtp"
    "libmtp"
    ## ntfs
    "ntfs-3g"
    ## logitech
    "piper"

    # fonts
    "noto-fonts"
    "noto-fonts-emoji"
    "ttf-dejavu"
    "ttf-jetbrains-mono"
    "ttf-ubuntu-font-family"

    # dotfiles
    "dash"
    "neovim"
    "picom"
    "rofi"
    "stow"
    ## apps
    "easyeffects"
    "emacs"
    "mpv"
    "yt-dlp"
    ## theme
    "arc-gtk-theme"
    "papirus-icon-theme"
    ## joshuto
    "catdoc"
    "bat"
    ## dwm
    "sxhkd"
    ## lightdm
    "numlockx"
    ## alacritty
    "redshift"
    "zsh"
    "zsh-completions"
    ## autostart
    "dunst"
    "feh"
    "polkit-gnome"
    ## zshrc
    "lolcat"
    ## scripts/dm-screenshot
    "maim"
    "xdotool"
    ## scripts/dm-screenshot && scripts/dm-videos
    "xclip"
    ## scripts/extract
    "unzip"
    ## scripts/statusbar
    "pacman-contrib"
)
