#!/usr/bin/env bash

# zsh cache
mkdir -p ${HOME}/.cache/zsh

# sddm config
doas sed -i -r 's/^(ForceHideCompletePassword=).*/\1"true"/g' /usr/share/sddm/themes/sugar-candy/theme.conf
doas systemctl enable sddm

# remove the screen saver
doas systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

# enable systemctl services
systemctl --user daemon-reload
systemctl --user enable setmicvolume
systemctl --user enable easyeffects

# update the shell
doas ln -sfT dash /usr/bin/sh
doas chsh -s /bin/zsh ${USER}

# install rust stable
rustup install stable
