#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm ttf-dejavu ttf-liberation \
    || ERROR "[config.russian]: Unable to install fonts"

sudo echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen \
    || LOG "[config.russian]: Unable to add russian to locales"

sudo locale-gen \
    || LOG "[config.russian]: Unable to update locales"

localectl set-x11-keymap --no-convert us,ru pc105 "" grp:alt_shift_toggle \
    || LOG "[config.russian]: Unable to change the keyboard layout"
